### ISSUE TITLE
[simulators] logs sometimes missing or late  

### ISSUE THREAD

**Issue by kkharji** [kkharji/xbase#95]
I started noticing this issue, not sure maybe it's related to recent Xcode release or perhaps something wrong with [process-stream](https://github.com/tami5/process-stream) crate.

**Comment by tami5** [comment]
Running `xcrun simctl launch —terminate-running-process —console <device-uid> <identifier-id>` produce identical results. Now I'm stuck wondering whether recent `xcrun simctl` upgrades created this problem and hopefully there's an alternative way to run `xcrun simctl`, or whether the problem is more with the project I'm testing or my machine.

In Xcode console though, it works fine
